FROM golang:1-alpine3.17

RUN apk add --no-cache git ca-certificates build-base su-exec olm-dev bash jq yq curl

COPY . /build
WORKDIR /build
RUN go build -o /gvoice

# Setup development stack using gow
RUN go install github.com/mitranim/gow@latest
RUN echo 'gow run /build $@' > /usr/bin/mautrix-gvoice \
    && chmod +x /usr/bin/mautrix-gvoice
VOLUME /data
